### ISSUE TITLE
Mac M1 issue

### ISSUE THREAD

**Issue by matigumma** [banbox/banexg#1]
```
package main

import (
	"fmt"
	"time"

	binance "github.com/banbox/banexg/binance"
)

func main() {
	symbol := "SOLUSDT"
	timeframe := "5m"
	options := map[string]interface{}{}

	app, err := binance.NewExchange(options)
	if err != nil {
		fmt.Println(err)
	}

	since := time.Now().Add(-30*time.Minute).Unix() * 1000

	ohlcv, err := app.FetchOHLCV(symbol, timeframe, since, 0, nil)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(ohlcv)
}


go run main.go
# github.com/banbox/banexg/utils
../go/pkg/mod/github.com/banbox/banexg@v0.2.0/utils/misc.go:248:5: dc.UseInt64 undefined (type *json.Decoder has no field or method UseInt64)
```
related to this:
[https://github.com/bytedance/sonic/issues/449](url)

**Comment by anyongjin** [comment]
Thanks for the feedback. I noticed that [449](https://github.com/bytedance/sonic/issues/449) mentioned that `UseInt64` is only valid for the `amd64` architecture, so I added the judgment now. 
`UseInt64` is called because Sonic uses float64 when deserializing int64 long integers, resulting in precision loss. So banexg call `UseInt64` to force the use of int64 to parse long integers to avoid precision loss. You can test whether there is such behavior under the mac m1 architecture. If you have an optimization solution, you are welcome to submit a merge request. I have added a reminder in the readme

**Comment by matigumma** [comment]
some tests:

![image](https://github.com/user-attachments/assets/a227e37e-1b62-4e09-9f97-8cb548d632d1)

![image](https://github.com/user-attachments/assets/a989544b-09d2-4161-96fe-d173b01a2f78)

![image](https://github.com/user-attachments/assets/d2a56ad6-3b11-468f-80b9-25b1a47bc917)


![image](https://github.com/user-attachments/assets/86990043-4713-4661-a9cd-58b8563b8e93)

commented:
![image](https://github.com/user-attachments/assets/bc531812-b219-45e1-b0ec-9890cc93a886)

**Comment by anyongjin** [comment]
It seems to be an incompatibility caused by changes in the new version of sonic. It has been fixed. Thanks for the feedback!
